import 'dart:convert';

/// Represents an error generated by an `API` object.
class APIError implements Exception {
  /// The cause of this exception.
  String message;

  /// An HTTP status code this exception will throw.
  int statusCode;

  APIError({this.message = 'Bad Request',
      this.statusCode = 400});

  @override
  String toString() {
    return "$statusCode: $message";
  }

  factory APIError.fromMap(Map data) {
    return new APIError(
      statusCode: (data['status_code']) as int,
      message: data['message']?.toString(),
    );
  }

  factory APIError.fromJson(String str) =>
      new APIError.fromMap(json.decode(str) as Map);

  /// Throws a 400 Bad Request error.
  factory APIError.badRequest(
          {String message = 'Bad Request'}) =>
      new APIError(message: message, statusCode: 400);

  /// Throws a 401 Not Authenticated error.
  factory APIError.notAuthenticated(
          {String message = 'Not Authenticated'}) =>
      new APIError(message: message, statusCode: 401);

  /// Throws a 403 Forbidden error.
  factory APIError.forbidden({String message = 'Forbidden'}) =>
      new APIError(message: message, statusCode: 403);

  /// Throws a 404 Not Found error.
  factory APIError.notFound({String message = 'Not Found'}) =>
      new APIError(message: message, statusCode: 404);
}